// Generated by CoffeeScript 1.3.3
(function() {
  var HTTP, request;

  request = require('request');

  HTTP = (function() {

    function HTTP(target, options) {
      this.target = target;
      this.options = options;
    }

    HTTP.prototype.start = function(callback, prefix) {
      var _this = this;
      if (prefix == null) {
        prefix = 'http';
      }
      return request.get({
        url: "" + prefix + "://" + this.target,
        timeout: this.options.timeout,
        headers: {
          'User-Agent': this.options.httpUserAgent
        }
      }, function(err, res, body) {
        if (body == null) {
          body = '';
        }
        if (err) {
          return callback({
            error: true
          });
        }
        return exports.runMiddleware(res, body, callback);
      });
    };

    return HTTP;

  })();

  exports.description = 'HTTP module';

  exports.port = 80;

  exports.Module = HTTP;

  exports.commands = function(commander, defaults) {
    defaults.httpUserAgent = 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)';
    return commander.option('--http-user-agent [string]', "User agent to use for the HTTP module [" + defaults.httpUserAgent + "]");
  };

}).call(this);
