// Generated by CoffeeScript 1.3.3
(function() {
  var Queue;

  Queue = (function() {

    function Queue(maxOperations) {
      if (maxOperations == null) {
        maxOperations = 1;
      }
      this.currentOperations = 0;
      this.queue = [];
    }

    Queue.prototype.run = function(callback) {
      var _this = this;
      if (!callback) {
        return;
      }
      this.currentOperations++;
      return callback(function() {
        _this.currentOperations--;
        return _this.run(_this.queue.shift());
      });
    };

    Queue.prototype.add = function(callback) {
      if (this.currentOperations === this.maxOperations) {
        return this.queue.push(callback);
      } else {
        return this.run(callback);
      }
    };

    return Queue;

  })();

  module.exports = Queue;

}).call(this);
