// Generated by CoffeeScript 1.3.3
(function() {
  var currentOperations, maxOperations, queue, run;

  currentOperations = 0;

  maxOperations = 0;

  queue = [];

  run = function(callback) {
    if (!callback) {
      return;
    }
    currentOperations++;
    return callback(function() {
      currentOperations--;
      return run(queue.shift());
    });
  };

  exports.maxOperations = function(operations) {
    return maxOperations = operations;
  };

  exports.add = function(callback) {
    if (currentOperations === maxOperations) {
      return queue.push(callback);
    } else {
      return run(callback);
    }
  };

}).call(this);
