// Generated by CoffeeScript 1.3.3
(function() {
  var fs, path;

  path = require('path');

  fs = require('fs');

  exports.IPv4ToLong = function(str) {
    var parts;
    parts = str.split('.');
    return parts[0] << 24 | parts[1] << 16 | parts[2] << 8 | parts[3] << 0;
  };

  exports.longToIPv4 = function(l) {
    return ((l >> 24) & 255) + '.' + ((l >> 16) & 255) + '.' + ((l >> 8) & 255) + '.' + ((l >> 0) & 255);
  };

  exports.rmdir = function(dir) {
    var file, loc, stats, _i, _len, _ref;
    if (!fs.existsSync(dir)) {
      return;
    }
    _ref = fs.readdirSync(dir);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      file = _ref[_i];
      loc = "" + dir + path.sep + file;
      stats = fs.statSync(loc);
      if (stats.isDirectory()) {
        exports.rmdir(loc);
      } else {
        fs.unlinkSync(loc);
      }
    }
    return fs.rmdirSync(dir);
  };

}).call(this);
