// Generated by CoffeeScript 1.3.3
(function() {

  exports.IPv4ToLong = function(str) {
    var parts;
    parts = str.split('.');
    return parts[0] << 24 | parts[1] << 16 | parts[2] << 8 | parts[3] << 0;
  };

  exports.longToIPv4 = function(l) {
    return ((l >> 24) & 255) + '.' + ((l >> 16) & 255) + '.' + ((l >> 8) & 255) + '.' + ((l >> 0) & 255);
  };

}).call(this);
