// Generated by CoffeeScript 1.3.3
(function() {
  var FTP, FTPClient;

  FTPClient = require('ftp');

  FTP = (function() {

    function FTP(target, options) {
      this.target = target;
      this.options = options;
    }

    FTP.prototype.start = function(callback) {
      var ftp;
      ftp = new FTPClient({
        host: this.target,
        connTimeout: this.options.timeout
      });
      ftp.on('error', function(err) {
        ftp.end();
        return callback({
          error: err
        });
      });
      ftp.on('timeout', function() {
        ftp.end();
        return callback({
          error: true
        });
      });
      ftp.on('connect', function() {
        return ftp.auth(function(err) {
          ftp.end();
          return callback({
            data: {
              Anonymous: err ? 'false' : 'true'
            }
          });
        });
      });
      return ftp.connect();
    };

    return FTP;

  })();

  exports.port = 21;

  exports.Module = FTP;

}).call(this);
