// Generated by CoffeeScript 1.3.3
(function() {
  var FTP, FTPClient;

  FTPClient = require('ftp');

  FTP = (function() {

    function FTP(target, options) {
      this.target = target;
      this.options = options;
    }

    FTP.prototype.start = function(callback) {
      var ftp, result, timeout;
      ftp = new FTPClient({
        host: this.target,
        connTimeout: this.options.timeout
      });
      result = {
        error: true
      };
      timeout = setTimeout(function() {
        return ftp.end();
      }, this.options.timeout * 2);
      ftp.on('error', function(err) {
        return ftp.end();
      });
      ftp.on('timeout', function() {
        return ftp.end();
      });
      ftp.on('close', function() {
        clearTimeout(timeout);
        return callback(result);
      });
      ftp.on('connect', function() {
        return ftp.auth(function(err) {
          result = {
            data: {
              anonymous: err ? 'false' : 'true'
            }
          };
          return ftp.end();
        });
      });
      return ftp.connect();
    };

    return FTP;

  })();

  exports.description = 'FTP module';

  exports.port = 21;

  exports.Module = FTP;

}).call(this);
