// Generated by CoffeeScript 1.3.3
(function() {
  var commands, ncrawl, options;

  commands = require('./system/commands');

  ncrawl = require('./system/ncrawl');

  options = commands.cli();

  if (options) {
    options.after = function() {
      return process.exit();
    };
    ncrawl(options);
  }

}).call(this);
