// Generated by CoffeeScript 1.3.3
(function() {
  var commands, ncrawl;

  commands = require('./system/commands');

  ncrawl = require('./system/ncrawl');

  ncrawl(commands.cli());

}).call(this);
