// Generated by CoffeeScript 1.3.3
(function() {
  var JSONStreamReporter;

  JSONStreamReporter = (function() {

    function JSONStreamReporter() {}

    JSONStreamReporter.prototype.info = function(info) {
      info.event = 'info';
      return console.log(JSON.stringify(info));
    };

    JSONStreamReporter.prototype.result = function(name, result) {
      result.event = 'result';
      return console.log(JSON.stringify(result));
    };

    return JSONStreamReporter;

  })();

  exports.Reporter = JSONStreamReporter;

  exports.progress = function(progress) {
    return console.log(JSON.stringify({
      event: 'progress',
      progress: progress
    }));
  };

}).call(this);
