// Generated by CoffeeScript 1.3.3
(function() {
  var JSONStreamReporter, log;

  log = function(obj) {
    return console.log(JSON.stringify(obj));
  };

  JSONStreamReporter = (function() {

    function JSONStreamReporter() {}

    JSONStreamReporter.prototype.info = function(info) {
      info.event = 'info';
      return log(info);
    };

    JSONStreamReporter.prototype.identify = function(data) {
      data.event = 'identify';
      return log(data);
    };

    JSONStreamReporter.prototype.result = function(name, result) {
      result.event = 'result';
      return log(result);
    };

    return JSONStreamReporter;

  })();

  exports.Reporter = JSONStreamReporter;

  exports.progress = function(data) {
    data.event = 'progress';
    return log(data);
  };

}).call(this);
