// Generated by CoffeeScript 1.3.3
(function() {
  var JSONReporter;

  JSONReporter = (function() {

    function JSONReporter() {}

    JSONReporter.prototype.finish = function(info, results, id) {
      return console.log(JSON.stringify({
        info: info,
        results: results,
        id: id,
        event: 'results'
      }));
    };

    return JSONReporter;

  })();

  exports.Reporter = JSONReporter;

}).call(this);
