// Generated by CoffeeScript 1.3.3
(function() {
  var HTTP, HTTPS;

  HTTP = require('../http/http');

  HTTPS = (function() {

    HTTPS.prototype.port = 443;

    function HTTPS(target, options) {
      this.http = new HTTP.Module(target, options);
    }

    HTTPS.prototype.start = function(callback) {
      return this.http.start(callback, 'https');
    };

    return HTTPS;

  })();

  exports.port = 443;

  exports.Module = HTTPS;

}).call(this);
